-- جداول إدارة الأفواج والرياضيين المنتمين إليها
create table if not exists public.athlete_groups (
    id bigint generated by default as identity primary key,
    name text not null,
    goal text not null default '',
    location text not null default '',
    circumstances text not null default '',
    notes text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.athlete_group_members (
    group_id bigint not null references public.athlete_groups(id) on delete cascade,
    athlete_id bigint not null references public.athletes(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (group_id, athlete_id)
);

alter table public.athlete_groups enable row level security;
alter table public.athlete_group_members enable row level security;

create policy "authenticated users manage athlete groups"
    on public.athlete_groups for all to authenticated using (true) with check (true);
create policy "authenticated users manage group members"
    on public.athlete_group_members for all to authenticated using (true) with check (true);