-- جدول دفعات تأمين المركز
CREATE TABLE public.insurance_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_date DATE NOT NULL,
    total_amount NUMERIC NOT NULL,
    athletes JSONB NOT NULL, -- سيتم تخزين مصفوفة بأسماء ومعرفات الرياضيين
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- تفعيل صلاحيات الوصول (RLS)
ALTER TABLE public.insurance_batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all operations"
    ON public.insurance_batches
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);