-- =====================================================================
-- جدول: samurai_competition
-- قاعة KARATE — سجل نقاط مسابقة الساموراي الصغير
-- انسخ هذا الكود وشغّله في قسم "SQL Editor" في لوحة Supabase
-- =====================================================================

CREATE TABLE public.samurai_competition (

    -- المعرّف الفريد (يتولد تلقائياً)
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- معرّف الرياضي (مفتاح أجنبي مرتبط بجدول الرياضيين)
    athlete_id        BIGINT      NOT NULL REFERENCES public.athletes(id) ON DELETE CASCADE,

    -- تاريخ منح/خصم النقطة
    date              DATE        NOT NULL,

    -- قيمة النقاط (يمكن أن تكون موجبة أو سالبة)
    points            NUMERIC(3, 1) NOT NULL,

    -- سبب منح/خصم النقطة
    reason            TEXT        NOT NULL,

    -- ملاحظات إضافية (اختياري)
    notes             TEXT,

    -- توقيت الإنشاء (يتولد تلقائياً)
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- إضافة RLS (Row Level Security) - موصى به
-- =====================================================================

-- تفعيل RLS على الجدول
ALTER TABLE public.samurai_competition ENABLE ROW LEVEL SECURITY;

-- سياسة: السماح للجميع بجميع العمليات (لأن التطبيق يعتمد على واجهة ومفتاح عام)
CREATE POLICY "Allow public all operations on samurai_competition"
    ON public.samurai_competition
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);


-- =====================================================================
-- فهرس للأداء (ترتيب سريع حسب تاريخ الرياضي)
-- =====================================================================
CREATE INDEX idx_samurai_competition_athlete_date
    ON public.samurai_competition (athlete_id, date DESC);