-- =====================================================================
-- جدول: training_sessions
-- قاعة KARATE — سجل الحصص التدريبية
-- انسخ هذا الكود وشغّله في قسم "SQL Editor" في لوحة Supabase
-- =====================================================================

CREATE TABLE public.training_sessions (

    -- المعرّف الفريد (يتولد تلقائياً)
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- تاريخ الحصة
    session_date      DATE        NOT NULL,

    -- عنوان الحصة (مثال: "تقنيات الضربات الأمامية")
    title             TEXT        NOT NULL,

    -- هدف الحصة (مثال: هدف بدني، مهاري...)
    session_goal      TEXT,

    -- طريقة التدريب (مثال: التدريب الدائري، الفتري...)
    training_method   TEXT,

    -- التمارين المستخدمة وأهدافها (نص واسع)
    exercises         TEXT,

    -- مدة الحصة بالدقائق
    duration_minutes  INT         CHECK (duration_minutes > 0),

    -- تقييم الحصة (من 1 إلى 5)
    rating_comprehension INT CHECK (rating_comprehension BETWEEN 1 AND 5),
    rating_discipline    INT CHECK (rating_discipline BETWEEN 1 AND 5),
    rating_enthusiasm    INT CHECK (rating_enthusiasm BETWEEN 1 AND 5),

    -- ملاحظات إضافية (اختياري)
    notes             TEXT,

    -- توقيت الإنشاء والتحديث (يتولدان تلقائياً)
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- إضافة RLS (Row Level Security) - اختياري لكن موصى به
-- =====================================================================

-- تفعيل RLS على الجدول
ALTER TABLE public.training_sessions ENABLE ROW LEVEL SECURITY;

-- سياسة: السماح للجميع بجميع العمليات (لأن التطبيق يعتمد على واجهة ومفتاح عام)
CREATE POLICY "Allow public all operations"
    ON public.training_sessions
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);


-- =====================================================================
-- فهرس للأداء (ترتيب سريع حسب التاريخ)
-- =====================================================================
CREATE INDEX idx_training_sessions_date
    ON public.training_sessions (session_date DESC);


-- =====================================================================
-- دالة تحديث updated_at تلقائياً عند التعديل
-- =====================================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_training_sessions_updated_at
    BEFORE UPDATE ON public.training_sessions
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();


-- =====================================================================
-- بيانات تجريبية (اختياري — احذفها من الإنتاج)
-- =====================================================================
INSERT INTO public.training_sessions (session_date, title, exercises, duration_minutes, notes) VALUES
(
    CURRENT_DATE - INTERVAL '7 days',
    'تقنيات الضربات الأمامية - Mae Geri',
    '1. Mae Geri (الركلة الأمامية): 3 × 20 تكرار لكل رجل - الهدف: الدقة والارتفاع
2. Oi Tsuki (الضربة المستقيمة): 3 × 30 تكرار - الهدف: تقوية التسليم والتوازن
3. Gedan Barai (الحجب السفلي): تمرين الإيقاع مع الشريك - الهدف: ردة الفعل
4. Kata Heian Shodan: تكرار كامل 5 مرات - الهدف: الحفظ والانتظام',
    90,
    'الرياضيون أبدوا تحسناً واضحاً في الدقة. يُنصح بمواصلة التركيز على وضعية القدمين.'
),
(
    CURRENT_DATE - INTERVAL '3 days',
    'تقنيات الدفاع والهجوم المدمج',
    '1. Jodan Uke (الحجب العلوي): بالإيقاع ثم مع الهجوم المضاد - 4 × 15
2. Uraken Uchi (ضربة ظهر الكف): تمرين الميتاي - 3 × 20
3. Combination: Uke + Gyaku Tsuki: 4 × 10 تبادل مع الشريك
4. Kumite خفيف (تطبيقي): 2 دقيقة × 3 جولات - ضبط المسافة والتوقيت',
    75,
    NULL
);
